- name: Ensure Podman is installed
  package:
    name: podman
    state: present

- name: Pull exporter images
  community.general.podman_image:
    name: "{{ item.image }}"
    state: present
  loop: "{{ exporters }}"

- name: Generate systemd unit files for exporters
  command: >
    podman generate systemd --name {{ item.name }}
    --restart-policy=always --files
  args:
    chdir: /etc/systemd/system
  loop: "{{ exporters }}"

- name: Reload systemd to recognize new unit files
  systemd:
    daemon_reload: yes

- name: Enable and start exporter services
  systemd:
    name: "container-{{ item.name }}.service"
    enabled: yes
    state: started
  loop: "{{ exporters }}"
