- name: Ensure Grafana PV directory exists on target worker node
  ansible.builtin.file:
    path: "{{ grafana_pv_path }}"
    state: directory
    owner: 472
    group: 472
    mode: '0755'
  delegate_to: "{{ grafana_pv_node }}"

- name: Create PersistentVolume for Grafana
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ grafana_pv_name }}"
      spec:
        capacity:
          storage: "{{ grafana_pv_size }}"
        accessModes:
          - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: "{{ grafana_sc_name }}"
        local:
          path: "{{ grafana_pv_path }}"
        nodeAffinity:
          required:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - "{{ grafana_pv_node }}"
