- name: Add Grafana Helm repository
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts

- name: Create a namespace for grafana (if not exists)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    api_version: v1
    kind: Namespace
    name: "{{ grafana_namespace }}"
    state: present

- name: Deploy Grafana via Helm
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_path }}"
    name: "{{ grafana_helm_release_name }}"
    chart_ref: "{{ grafana_helm_chart_name }}"
    release_namespace: "{{ grafana_namespace }}"
    create_namespace: false
    values:
      persistence:
        enabled: true
        storageClassName: "{{ grafana_pv_sc_name }}"
        accessModes:
          - ReadWriteOnce
        size: "{{ grafana_pv_size }}"
      adminPassword: "admin123"
      service:
        type: NodePort
        nodePort: 32000
