#
# Before installing Kubernetes, We need to uninstall iptables and
# install iptables-nft to resolve the package conflict
#
- name: Collect installed packages
  package_facts:
    manager: pacman

- name: Remove iptables to resolve conflicts
  command: pacman -Rdd --noconfirm iptables
  when: "'iptables' in ansible_facts.packages"
  ignore_errors: true

- name: Remove iproute2 to resolve conflicts
  command: pacman -Rdd --noconfirm iproute2
  when: "'iproute2' in ansible_facts.packages"
  ignore_errors: true

- name: Install required networking packages
  pacman:
    name:
      - iptables-nft
      - iproute2
    state: present
    update_cache: yes

- name: Install Kubernetes packages
  pacman:
    name: "{{ k8s_packages }}"
    state: present
    update_cache: yes
