# Install necessary packages
- import_tasks: install_kubernetes.yaml
- import_tasks: install_docker.yaml

# Reboot if required
- import_tasks: reboot.yaml

# Enable and start necessary services
- import_tasks: enable_kubelet.yaml
- import_tasks: enable_docker.yaml
