- name: Ensure Secret namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    api_version: v1
    kind: Namespace
    name: "{{ ceph_namespace }}"
    state: present
  delegate_to: k8s-control-node-1

- name: Create CephFS CSI Secret
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ ceph_secret_name }}"
        namespace: "{{ ceph_namespace }}"
      stringData:
        userID: "{{ ceph_user_name }}"
        userKey: "{{ ceph_user_secret }}"
      type: Opaque
  delegate_to: k8s-control-node-1

