- name: Ensure Secret namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ ceph_namespace }}"
    state: present

- name: Create CephFS CSI Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ ceph_secret_name }}"
        namespace: "{{ ceph_namespace }}"
      stringData:
        userID: "{{ ceph_user }}"
        userKey: "{{ ceph_user_secret }}"
      type: Opaque
