- name: Add Ceph CSI Helm repo
  community.kubernetes.helm_repository:
    name: "{{ csi_helm_release_name }}"
    repo_url: "{{ csi_helm_repo_url }}"
    state: present
  delegate_to: k8s-control-node-1

- name: Deploy CephFS CSI Helm chart
  community.kubernetes.helm:
    kubeconfig: "{{ kubeconfig_path }}"
    name: "{{ csi_helm_release_name }}"
    chart_ref: "{{ csi_helm_chart_name }}"
    release_namespace: "{{ ceph_namespace }}"
    create_namespace: true
    values:
      csiPlugin:
        rbac:
          create: true
        nodeStageSecretName: "{{ csi_secret_name }}"
        nodeStageSecretNamespace: "{{ csi_secret_namespace }}"
      provisioner:
        rbac:
          create: true
        provisionerSecretName: "{{ csi_secret_name }}"
        provisionerSecretNamespace: "{{ csi_secret_namespace }}"
  delegate_to: k8s-control-node-1
