#
# Common configurations that every K8s node requires
#
- name: Apply common configuration to all K8s nodes
  hosts: k8s_all
  become: yes
  roles:
    - k8s_common

#
# Init K8s control plane
#
- name: Init control plane nodes
  hosts: k8s_control
  become: yes
  roles:
    - k8s_control

#
# Join K8s workers
#
- name: Join worker nodes
  hosts: k8s_worker
  become: yes
  roles:
    - k8s_worker

#
# Apply K8s cluster manifests
#
- name: Apply K8s cluster manifests
  hosts: k8s_control
  become: yes
  roles:
    - manifests