- name: Apply common configuration to all nodes
  hosts: all:!localhost
  become: yes
  roles:
    - common

##### Kubernetes ####################################################
- name: Apply common configurations to all K8s nodes
  hosts: k8s_all
  become: yes
  roles:
    - k8s_common

- name: Initialize K8s control plane nodes
  hosts: k8s-control-node-1
  become: yes
  roles:
    - k8s_control

- name: Join K8s worker nodes to the cluster
  hosts: k8s_workers
  become: yes
  roles:
    - k8s_workers

- name: Overlay K8s cluster manifests
  hosts: k8s-control-node-1
  become: yes
  roles:
    - k8s_manifests

##### Ceph ##########################################################
- name: Distribute SSH key pairs to bootstrap/storage
  hosts: localhost
  roles:
    - ceph_prelude

- name: Apply common configurations to all Ceph nodes
  hosts: ceph_all
  become: yes
  roles:
    - ceph_common

- name: Bootstrap Ceph cluster
  hosts: ceph-node-1
  become: yes
  roles:
    - ceph_bootstrap

- name: Deploy CephFS and mount it from K8s cluster
  hosts: ceph-node-1
  become: yes
  roles:
    - cephfs_csi_setup
