#
# Common configurations that every node requires
#
- name: Apply common configuration to all nodes
  hosts: all
  become: yes
  roles:
    - common

#
# Init control plane
#
- name: Init control plane nodes
  hosts: control
  become: yes
  roles:
    - k8s_control

#
# Join workers
#
- name: Join worker nodes
  hosts: workers
  become: yes
  roles:
    - k8s_worker

#
# Deploy game server
#
- name: Deploy game_server
  hosts: control
  become: yes
  roles:
    - game_server

#
# Deploy reverse proxy
#
- name: Deploy reverse proxy
  hosts: control
  become: yes
  roles:
    - reverse_proxy

#
# Deploy load balacner
#
- name: Deploy load balacner
  hosts: control
  become: yes
  roles:
    - load_balancer