#
# Common configurations that every node requires
#
- name: Apply common configuration to all nodes
  hosts: all
  become: yes
  roles:
    - common

#
# Init control plane
#
- name: Init control plane nodes
  hosts: control
  become: yes
  roles:
    - k8s_control

#
# Join workers
#
- name: Join worker nodes
  hosts: workers
  become: yes
  roles:
    - k8s_worker

#
# Apply K8s cluster manifests
#
- name: Apply K8s cluster manifests
  hosts: control
  become: yes
  roles:
    - manifests