- name: Clone k8s-cluster-manifests repo from GitHub
  git:
    repo: "{{ overlay_url }}"
    dest: "{{ overlay_dest }}"
    version: "{{ overlay_version }}"
    force: yes

- name: Build single manifest file from Kustomize
  command:
    cmd: kustomize build {{ overlay_dest }}/{{ overlay_name }} -o {{ overlay_yaml }}

- name: Apply generated manifest with Ansible k8s module
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    src: "{{ overlay_yaml }}"
