- name: Create PersistentVolume for Jenkins
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ jenkins_pv_name }}"
      spec:
        capacity:
          storage: "{{ jenkins_pv_size }}"
        accessModes:
          - ReadWriteOnce
        storageClassName: "{{ jenkins_sc_name }}"
        persistentVolumeReclaimPolicy: Retain
        hostPath:
          path: "{{ jenkins_pv_path }}"
        nodeAffinity:
          required:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - "{{ jenkins_pv_node }}"
