metallb_url: "https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml"
overlay_url: "https://github.com/Tail-R/k8s-cluster-manifests.git"
overlay_dest: "/home/admin/ansible/manifests/k8s-cluster-manifests"
overlay_version: "main"
overlay_name: "overlays/dev"
generated_manifest: "/tmp/dev.yaml"
kubeconfig_path: "/etc/kubernetes/admin.conf"
