# K8s resources
grafana_namespace: "monitoring"
grafana_pv_name: "grafana-pv"
grafana_pv_path: "/mnt/data/grafana"
grafana_pv_sc_name: "local-storage"
grafana_pv_size: "5Gi"
grafana_pv_node: "k8s-worker-node-1"

# Grafana configurations
grafana_helm_repo_url: "https://grafana.github.io/helm-charts"
grafana_helm_release_name: "grafana"
grafana_helm_chart_name: "grafana/grafana"
