- name: Get Flannel manifest
  get_url:
    url: "{{ flannel_url }}"
    dest: "{{ flannel_dest }}"

- name: Apply Flannel CNI manifest
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: "{{ flannel_dest }}"
