- name: Get Flannel manifest
  get_url:
    url: "{{ flannel_url }}"
    dest: "{{ flannel_dest }}"

- name: Apply Flannel CNI manifest
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: "{{ flannel_dest }}"

- name: Wait for all Flannel pods to be Ready
  command: >
    kubectl --kubeconfig={{ kubeconfig_path }} -n kube-flannel \
    wait --for=condition=Ready pod -l app=flannel --timeout=300s
  changed_when: false
