- name: Check if Helm is already installed
  command: helm version --short
  register: helm_check
  ignore_errors: yes

- name: Install Helm using official install script
  shell: >
    curl -fsSL {{ helm_url }} | bash -s -- --version {{ helm_version }}
  args:
    executable: /bin/bash
  when: helm_check.rc != 0

- name: Verify Helm installation
  command: helm version --short
  register: helm_version_output

- debug:
    msg: "Installed Helm version: {{ helm_version_output.stdout }}"
