# Initialize the K8s control plane
- import_tasks: init_k8s_control.yaml

# Install Helm
- import_tasks: install_helm.yaml

# Apply CNI (Container Network Interface)
- import_tasks: apply_flannel_cni.yaml
