- name: Create BusyBox Pod mounting CephFS PVC
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: cephfs-busybox-pod
        namespace: "{{ app_namespace }}"
      spec:
        containers:
          - name: busybox
            image: busybox:1.36
            command: ["sleep", "3600"]
            volumeMounts:
              - name: cephfs-volume
                mountPath: /mnt/data
        volumes:
          - name: cephfs-volume
            persistentVolumeClaim:
              claimName: "{{ ceph_pvc_name }}"
  delegate_to: k8s-control-node-1
