- name: Join the node to the Kubernetes cluster
  command: "{{ hostvars[groups['control'][0]].join_command }}"
  args:
    creates: "{{ kubeletconfig_path }}"
  when: hostvars[groups['control'][0]].join_command is defined
