- name: Create PersistentVolume for Prometheus
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ prometheus_pv_name }}"
      spec:
        capacity:
          storage: "{{ prometheus_pv_size }}"
        accessModes:
          - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: "{{ prometheus_pv_storage_class }}"
        local:
          path: "{{ prometheus_pv_path }}"
        nodeAffinity:
          required:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - "{{ prometheus_pv_node }}"
