- name: Ensure Promehteus PV directory exists on target worker node
  ansible.builtin.file:
    path: "{{ prometheus_pv_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  delegate_to: k8s-worker-node-1

- name: Create PersistentVolume for Prometheus
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ prometheus_pv_name }}"
      spec:
        capacity:
          storage: "{{ prometheus_pv_size }}"
        accessModes:
          - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: "{{ prometheus_pv_sc_name }}"
        local:
          path: "{{ prometheus_pv_path }}"
        nodeAffinity:
          required:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - "{{ prometheus_pv_node }}"
