- name: Ensure Prometheus namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    api_version: v1
    kind: Namespace
    name: "{{ prometheus_namespace }}"
    state: present

- name: Add prometheus-community Helm repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "{{ prometheus_helm_repo_url }}"
    state: present

- name: Deploy Prometheus using Helm
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_path }}"
    name: "{{ prometheus_helm_release_name }}"
    chart_ref: "{{ prometheus_helm_chart_name }}"
    chart_version: "{{ prometheus_helm_chart_version }}"
    namespace: "{{ prometheus_namespace }}"
    values:
      server:
        global:
          scrape_interval: "{{ prometheus_scrape_interval }}"
        nodeSelector:
          kubernetes.io/hostname: "{{ prometheus_pv_node }}"
        persistentVolume:
          enabled: true
          storageClass: "{{ prometheus_sc_name }}"
          size: "{{ prometheus_pv_size }}"
      extraScrapeConfigs: |
        - job_name: "lm-sensors-exporter"
          scheme: http
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names: ["{{ prometheus_namespace }}"]
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              action: keep
              regex: lm-sensors-exporter-headless
          metrics_path: /metrics

        - job_name: "ceph-mgr"
          static_configs:
            - targets:
                - "192.168.100.40:9283"
                - "192.168.100.41:9283"
                - "192.168.100.42:9283"
      alertmanager:
        enabled: false
      kube-state-metrics:
        enabled: true
      prometheus-node-exporter:
        enabled: true
