- name: Ensure prometheus namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    api_version: v1
    kind: Namespace
    name: "{{ prometheus_namespace }}"
    state: present

- name: Add prometheus-community Helm repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "{{ prometheus_helm_repo_url }}"
    state: present

- name: Deploy Prometheus using Helm with extraScrapeConfigs
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_path }}"
    name: "{{ prometheus_helm_release_name }}"
    chart_ref: "{{ prometheus_helm_chart_name }}"
    chart_version: "{{ prometheus_helm_chart_version }}"
    namespace: "{{ prometheus_namespace }}"
    values:
      alertmanager:
        enabled: false
      nodeExporter:
        enabled: true
      server:
        extraScrapeConfigs: |
          - job_name: 'ceph-mgr'
            static_configs:
              - targets: ['192.168.100.42:9283']
            metrics_path: /metrics
            scrape_interval: 30s
        persistentVolume:
          enabled: true
          storageClass: "{{ prometheus_pv_sc_name }}"
          size: "{{ prometheus_pv_size }}"
        nodeSelector:
          kubernetes.io/hostname: "{{ prometheus_pv_node }}"
      global:
        scrape_interval: "{{ prometheus_scrape_interval }}"
