- name: Ensure base-devel and git are installed
  pacman:
    name:
      - base-devel
      - git
    state: present

- name: Create a build user
  user:
    name: builduser
    shell: /bin/bash
    create_home: yes
    groups: wheel
    state: present

- name: Allow builduser to use sudo without password
  copy:
    dest: /etc/sudoers.d/builduser-nopasswd
    content: 'builduser ALL=(ALL) NOPASSWD: ALL'
    mode: '0440'

- name: Remove existing yay build directory
  file:
    path: /tmp/yay-bin
    state: absent

- name: Install yay (AUR helper) if not present
  become_user: builduser
  shell: |
    cd /tmp
    git clone https://aur.archlinux.org/yay-bin.git
    cd yay-bin
    makepkg -si --noconfirm
  args:
    creates: /usr/bin/yay

- name: Remove the permission of using sudo for builduser
  file:
    path: /etc/sudoers.d/builduser-nopasswd
    state: absent